---
- hosts: 172.16.10.177
  gather_facts: no
  connection: local
  vars:
    aci_login: &aci_login
      host: 172.16.10.177
      username: 'admin'
      password: 'MyACILab23!'
      validate_certs: false

  # API: https://{{apic}}/api/aaaLogin.json

  tasks:
    - name: Read contents of .csv file
      community.general.read_csv:
        path: read_csv.csv
      register: tenant_vars
      tags:
        - raw
        - tn

    - name: Create tenant
      cisco.aci.aci_tenant:
        # Manage tenants (fv:Tenant)
        # API: https://{{apic}}/api/node/mo/uni/tn-{{TENANT}}.json
        <<: *aci_login
        tenant: "{{ item.TENANT }}"
        description: "{{ item.DESCR }}"
        owner_tag: "{{ item.OWNER_TAG }}"
        state: "{{ item.STATE }}"
      loop: "{{ tenant_vars.list }}"
      loop_control:
        label: "{{ item.TENANT }}"