---
- hosts: 172.16.10.177
  gather_facts: no
  connection: local
  vars:
    aci_login: &aci_login
      host: 172.16.10.177
      username: 'admin'
      password: 'MyACILab23!'
      validate_certs: false


  tasks:
    - name: Create a Snapshot
      # API: https://{{apic}}/api/aaaLogin.json
      cisco.aci.aci_config_snapshot:
        <<: *aci_login
        state: present
        export_policy: config_backup
        max_count: 10
        description: Backups taken by MATLAB Test.
      delegate_to: localhost

    - name: Create a local user
      cisco.aci.aci_aaa_user:
        <<: *aci_login
        aaa_user: matlab_ansible
        aaa_password: MatLab123!
        aaa_password_lifetime:
        aaa_password_update_required: no
        expiration: never
        expires: no
        email: admin@matlab.com
        first_name: Matador
        last_name: Laborador
        validate_certs: no
        state: present
      delegate_to: localhost

    - name: Add user to admin group
        cisco.aci.aci_rest:
          <<: *aci_login
          path: /api/node/mo/uni/usertext/user-matlab_ansible/userdomain-all.json
          method: post
          content: |
            {"aaaUserDomain": 
              {"attributes": 
                {"name": "all",
                "rn": "userdomain-all"},
                "children": [
                  {"aaaUserRole": {"attributes": {"name": "admin",
                  "privType": "writePriv", "rn": "role-admin"}}}
                ] }}